// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYUX4KUsCqZeQHhaOfpcZELXfMv1PBt0',
    appId: '1:979532823571:web:f7c0abd09ba37b08b793e6',
    messagingSenderId: '979532823571',
    projectId: 'foodapp-55c45',
    authDomain: 'foodapp-55c45.firebaseapp.com',
    storageBucket: 'foodapp-55c45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3d4fO_-YNekkAlHRRlTGt_ITA-LKAW4',
    appId: '1:979532823571:android:b0be4057b5a51062b793e6',
    messagingSenderId: '979532823571',
    projectId: 'foodapp-55c45',
    storageBucket: 'foodapp-55c45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFWguTxGj0YkOhaepyxHoHH8vi6_D9wo',
    appId: '1:979532823571:ios:bdc8c3aecf2eac2db793e6',
    messagingSenderId: '979532823571',
    projectId: 'foodapp-55c45',
    storageBucket: 'foodapp-55c45.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlFWguTxGj0YkOhaepyxHoHH8vi6_D9wo',
    appId: '1:979532823571:ios:bdc8c3aecf2eac2db793e6',
    messagingSenderId: '979532823571',
    projectId: 'foodapp-55c45',
    storageBucket: 'foodapp-55c45.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBYUX4KUsCqZeQHhaOfpcZELXfMv1PBt0',
    appId: '1:979532823571:web:4b618514158c5c90b793e6',
    messagingSenderId: '979532823571',
    projectId: 'foodapp-55c45',
    authDomain: 'foodapp-55c45.firebaseapp.com',
    storageBucket: 'foodapp-55c45.appspot.com',
  );
}
